import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { ReactQueryClientProvider } from '@/components/ReactQueryClientProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>

export default function RootLayout(props: RootLayoutProps) {
  const {
    children,
  } = props

  return (
    <ReactQueryClientProvider>
      <html className="dark" lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
}
