# fly.toml app configuration file generated for backend-shy-dawn-8299 on 2024-08-29T15:10:03+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-shy-dawn-8299'
primary_region = 'syd'
console_command = '/rails/bin/rails console'

[build]

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3002
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
