name: Deploy Frontend
on:
  push:
    branches:
      - github-actions-video
jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - run: echo "Deploying Frontend"